#!/usr/bin/env python3
"""Prepare a flat arXiv submission bundle from paper/ sources."""

from __future__ import annotations

import argparse
import shutil
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = ROOT / "paper"
DEFAULT_DIST = ROOT / "dist" / "arxiv"
ARXIV_README = "00README.txt"
TARBALL_NAME = "quantun-ia-paper.tar.gz"

SOURCE_GLOBS = (
    "main.tex",
    "references.bib",
    "arxiv_metadata.yaml",
    "sections/*.tex",
    "tables/*.tex",
    "figures/*.pdf",
)


def collect_paper_sources(paper_dir: Path = PAPER_DIR) -> list[Path]:
    """Return existing paper source paths relative to paper_dir."""
    sources: list[Path] = []
    for pattern in SOURCE_GLOBS:
        sources.extend(sorted(paper_dir.glob(pattern)))
    return [p for p in sources if p.is_file()]


def build_readme_text() -> str:
    """Return arXiv 00README.txt compiler instructions."""
    return f"""{ARXIV_README}
main.tex        — document entry point
sections/       — section TeX files (\\input from main.tex)
tables/         — holdout summary tables (\\input from sections/results.tex)
figures/        — PDF figures (\\includegraphics from sections/results.tex)
references.bib  — bibliography

To compile:
  pdflatex main.tex
  bibtex main
  pdflatex main.tex
  pdflatex main.tex

Generated by scripts/prepare_arxiv_submission.py (quantun-ia).
"""


def prepare_arxiv_submission(
    paper_dir: Path = PAPER_DIR,
    dist_dir: Path = DEFAULT_DIST,
    *,
    skip_pdf_check: bool = False,
) -> list[Path]:
    """Copy paper sources into dist/arxiv/ and create tarball. Returns artifact paths."""
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    dist_dir.mkdir(parents=True)

    artifacts: list[Path] = []
    for src in collect_paper_sources(paper_dir=paper_dir):
        rel = src.relative_to(paper_dir)
        dest = dist_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        artifacts.append(dest)

    pdf_src = paper_dir / "main.pdf"
    if pdf_src.is_file():
        dest_pdf = dist_dir / "main.pdf"
        shutil.copy2(pdf_src, dest_pdf)
        artifacts.append(dest_pdf)
    elif not skip_pdf_check:
        raise FileNotFoundError(
            "main.pdf missing — run `make paper-build` before `make arxiv-bundle`"
        )

    readme = dist_dir / ARXIV_README
    readme.write_text(build_readme_text(), encoding="utf-8")
    artifacts.append(readme)

    tarball = dist_dir / TARBALL_NAME
    with tarfile.open(tarball, "w:gz") as archive:
        for path in sorted(dist_dir.iterdir()):
            if path.name == TARBALL_NAME:
                continue
            archive.add(path, arcname=path.name)
    artifacts.append(tarball)

    return artifacts


def main() -> int:
    parser = argparse.ArgumentParser(description="Bundle paper/ for arXiv upload")
    parser.add_argument(
        "--dist",
        type=Path,
        default=DEFAULT_DIST,
        help="Output directory (default: dist/arxiv)",
    )
    parser.add_argument(
        "--skip-pdf-check",
        action="store_true",
        help="Bundle TeX sources without requiring main.pdf",
    )
    args = parser.parse_args()

    try:
        artifacts = prepare_arxiv_submission(
            dist_dir=args.dist,
            skip_pdf_check=args.skip_pdf_check,
        )
    except FileNotFoundError as exc:
        print(exc)
        return 1

    print(f"arXiv bundle ready at {args.dist} ({len(artifacts)} artifacts)")
    print(f"  Upload: {args.dist / TARBALL_NAME}")
    print("  See docs/arxiv.md for submission steps.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
