"""Dataset provenance and patient-profile plausibility checks for the CV clinic."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from src.application.human_cv_scorer import PatientProfile
from src.data.open_manifest import get_dataset, load_manifest, validate_open_data

OriginKind = Literal["synthetic", "real_world", "unknown"]
TrustLevel = Literal["verified_synthetic", "verified_real_world", "unverified", "implausible_input"]

ROOT = Path(__file__).resolve().parents[2]

SYNTHETIC_DATASET_IDS = frozenset({"synthea_cv_risk_v1"})
REAL_WORLD_DATASET_IDS = frozenset({"higgs_v1", "breast_cancer", "pima_diabetes"})


@dataclass(frozen=True)
class DatasetProvenanceResult:
    dataset_id: str
    origin: OriginKind
    verified: bool
    source_mode: str | None
    description: str
    license_name: str
    source_url: str
    has_phi: bool
    trust_level: TrustLevel
    issues: tuple[str, ...]

    @property
    def is_synthetic(self) -> bool:
        return self.origin == "synthetic"

    @property
    def badge_label(self) -> str:
        if self.origin == "synthetic":
            return "SYNTHETIC DATA"
        if self.origin == "real_world":
            return "REAL-WORLD DATA"
        return "UNKNOWN ORIGIN"

    @property
    def badge_help(self) -> str:
        if self.is_synthetic:
            return (
                "Generated by Synthea — no real patients. "
                "Scores show model behaviour on simulated EHR rows, not clinical truth."
            )
        if self.origin == "real_world":
            return "Observed or published dataset — not synthetic simulation."
        return "Dataset origin could not be determined from the manifest."


@dataclass(frozen=True)
class ProfileValidationResult:
    is_plausible: bool
    trust_level: Literal["plausible", "review", "implausible"]
    warnings: tuple[str, ...]
    checks_passed: int
    checks_total: int

    @property
    def summary(self) -> str:
        if not self.is_plausible:
            return "Profile has implausible values — check inputs before trusting the score."
        if self.warnings:
            return "Profile looks plausible with minor flags — compare relative risk, not absolute %."
        return "Profile values are within normal clinical ranges."


def _origin_for_dataset(dataset_id: str, description: str) -> OriginKind:
    if dataset_id in SYNTHETIC_DATASET_IDS:
        return "synthetic"
    if dataset_id in REAL_WORLD_DATASET_IDS:
        return "real_world"
    desc = description.lower()
    if "synthea" in desc or "synthetic" in desc:
        return "synthetic"
    if "uci" in desc or "real" in desc:
        return "real_world"
    return "unknown"


def _read_source_mode(root: Path, dataset: dict) -> str | None:
    stats_path = root / "data" / "open" / dataset["path"] / dataset["files"].get("stats", "stats.json")
    if not stats_path.is_file():
        return None
    try:
        payload = json.loads(stats_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    mode = payload.get("source_mode")
    return str(mode) if mode else None


def check_dataset_provenance(
    dataset_id: str,
    *,
    root: Path | None = None,
) -> DatasetProvenanceResult:
    """Verify manifest checksums and classify dataset as synthetic vs real-world."""
    root = root or ROOT
    manifest = load_manifest(root / "data" / "open" / "manifest.json")
    dataset = get_dataset(manifest, dataset_id)
    ok, issues = validate_open_data(root, dataset_id=dataset_id)
    origin = _origin_for_dataset(dataset_id, dataset.get("description", ""))
    source_mode = _read_source_mode(root, dataset)

    if origin == "synthetic":
        trust: TrustLevel = "verified_synthetic" if ok else "unverified"
    elif origin == "real_world":
        trust = "verified_real_world" if ok else "unverified"
    else:
        trust = "unverified"

    return DatasetProvenanceResult(
        dataset_id=dataset_id,
        origin=origin,
        verified=ok,
        source_mode=source_mode,
        description=dataset.get("description", ""),
        license_name=dataset.get("license", "unknown"),
        source_url=dataset.get("source_url", ""),
        has_phi=origin == "real_world" and "synthetic" not in dataset.get("description", "").lower(),
        trust_level=trust,
        issues=tuple(issues),
    )


def validate_patient_profile(profile: PatientProfile) -> ProfileValidationResult:
    """Check whether hand-entered vitals look clinically plausible (not synthetic demo defaults)."""
    warnings: list[str] = []
    passed = 0
    total = 0

    def check(condition: bool, ok_msg: bool, warning: str) -> None:
        nonlocal passed, total
        total += 1
        if condition:
            passed += 1
        else:
            warnings.append(warning)

    check(18 <= profile.age_years <= 110, True, f"Age {profile.age_years:.0f} outside 18–110 years")
    check(10.0 <= profile.bmi <= 60.0, True, f"BMI {profile.bmi:.1f} outside 10–60")
    check(70 <= profile.systolic_bp <= 250, True, f"Systolic BP {profile.systolic_bp:.0f} outside 70–250 mmHg")
    check(40 <= profile.diastolic_bp <= 150, True, f"Diastolic BP {profile.diastolic_bp:.0f} outside 40–150 mmHg")
    check(profile.systolic_bp > profile.diastolic_bp, True, "Systolic BP must exceed diastolic BP")
    check(80 <= profile.total_cholesterol <= 400, True, "Total cholesterol outside 80–400 mg/dL")
    check(15 <= profile.hdl <= 120, True, "HDL outside 15–120 mg/dL")

    if profile.age_years < 30 and profile.prior_mi:
        warnings.append("Prior MI in a patient under 30 is rare — double-check age/history")
    if profile.age_years < 25 and profile.prior_stroke:
        warnings.append("Prior stroke in a patient under 25 is rare — double-check age/history")
    if profile.bmi < 17 and not profile.diabetes:
        warnings.append("Very low BMI without diabetes — verify weight/height inputs")

    is_plausible = passed == total and not any(
        "outside" in w or "must exceed" in w for w in warnings
    )
    if not is_plausible:
        trust: Literal["plausible", "review", "implausible"] = "implausible"
    elif warnings:
        trust = "review"
    else:
        trust = "plausible"

    return ProfileValidationResult(
        is_plausible=is_plausible,
        trust_level=trust,
        warnings=tuple(warnings),
        checks_passed=passed,
        checks_total=total,
    )
